### ISSUE TITLE
Migrate to postcss-preset-env (postcss-cssnext deprecated)

### ISSUE THREAD

**Issue by jacobq** [mansona/ember-cli-notifications#220]
```
WARN deprecated postcss-cssnext@3.1.0: 'postcss-cssnext' has been deprecated in favor of 'postcss-preset-env'. Read more at https://moox.io/blog/deprecating-cssnext/
```

Would you like a PR?

**Comment by ntodd** [comment]
This now appears to be causing a warning due to outdated dependencies.

The deprecated `postcss-cssnext` depends on an outdated version of `autoprefixer` that depends on older versions of `caniuse-lite` and 'browserslist`.

This doesn't appear to be breaking anything, but I'm now getting the warning:

```
Browserslist: caniuse-lite is outdated. Please run next command `yarn upgrade caniuse-lite browserslist`
```

Everything is locked due to `postcss-cssnext`, so it looks like this should be updated. @jacobq did you ever get a PR ready?

**Comment by mansona** [comment]
This is fixed in https://github.com/mansona/ember-cli-notifications/pull/251#issuecomment-552737340 🎉 let me know if you have any questions 👍
