### ISSUE TITLE
How do notifications get into the component?

### ISSUE THREAD

**Issue by firstsano** [mansona/ember-cli-notifications#231]
I'm looking through the source code and I'm confused. How do notifications, that are stored in singletone-service's prop, get into the component, which displays them?

**Comment by mansona** [comment]
I think it's because of the initializer in the app folder https://github.com/ynnoj/ember-cli-notifications/blob/master/app/initializers/notifications.js

I think if I'm reading this correctly it will be injected into all components so you have access to it. I personally inject the service manually every time that I actually use it

**Comment by firstsano** [comment]
I use it through manual injecting too, and that initializer executes only when it's configured to. At first I thought that if the service was an ArrayProxy itself then a display of notifications depended on the name of injecting service, i.e. we've injected 'notifications' to controller and they've displayed as 'notifications' passed to component. But I've tried using something like this:
```
notify: service('notification-messages'),
```
and it still works. So I presume that the service uses some property called 'notifications' behind the curtain. But I don't see where. Any ideas?

**Comment by firstsano** [comment]
Oops, missed the part:
```
application.inject('component:notification-container', 'notifications', 'service:notification-messages');
application.inject('component:notification-message', 'notifications', 'service:notification-messages');
```
My bad, I guess everything is clear now.
Thanks!
