### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by maxx1128** [mansona/ember-cli-notifications#252]
Getting a GitHub Pages 404 error page - http://ynnoj.github.io/ember-cli-notifications/

**Comment by mansona** [comment]
so that URL will now always give you a 404 page 🤔 I am moving the documentation onto Netlify so that we don't have this issue any more but for now while we're in transition we won't be able to fix everything. Once https://github.com/mansona/ember-cli-notifications/pull/251 is merged we can update all links to Netlify

I have updated the link at the top of the GitHub to point to http://mansona.github.io/ember-cli-notifications/ for now, was that the link that is broken for you?

**Comment by maxx1128** [comment]
That link is working, thanks!
