### ISSUE TITLE
SyntaxError: expected expression, got '?'

### ISSUE THREAD

**Issue by a8nJ** [mansona/ember-cli-notifications#298]
This code:

https://github.com/mansona/ember-cli-notifications/blob/6b326728b47e69b29a3b00eacf5c9555c17fae0b/addon/services/notifications.js#L25-L33

Gives me this:

~~~
SyntaxError: expected expression, got '?'
~~~

The issue is `??`:

https://developer.mozilla.org/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#Implementation_Progress

That syntax has not been standardized, and does not work with my browser
(Waterfox 2020.10).

**Comment by a8nJ** [comment]
Here is another approach, only an extra 30 characters:

~~~js
const r = 'autoClear', s = 'clearDuration', t = Ember.Object.create({
   message: e.message,
   type: e.type || "info",
   [r]: !(r in e) ? !(r in n) ? !1 : n[r] : e[r],
   [s]: !(s in e) ? !(s in n) ? 3200 : n[s] : e[s],
   onClick: e.onClick,
   htmlContent: e.htmlContent || !1,
   cssClasses: e.cssClasses
});
~~~

**Comment by a8nJ** [comment]
https://github.com/rust-lang/crates.io/issues/2984

**Comment by a8nJ** [comment]
looks like this broke it: https://github.com/mansona/ember-cli-notifications/commit/594cb05e41790059d40b7fdaca987b76c9aca0d1

@jacobq

**Comment by Turbo87** [comment]
this project is using ember-cli-babel, and if the app that's using it specifies browser targets that don't support this feature then it will be transpiled back to older JS code. in other words: this is working as expected on this side.

**Comment by mansona** [comment]
so yes @Turbo87 is correct, this is something that automatically gets transpiled out when you're using babel (which all Ember apps are using)

To debug your problem we need 2 things: can you share your targets file from your app (which you can get in `config/targets.js`) and can you tell me what version of ember-cli-babel you are using in your app? It might be useful to know what version of ember-cli you are using 🤔  but the main issue is ember-cli-babel 👍

**Comment by a8nJ** [comment]
I have no idea what a targets file is.

I encountered this error by visiting https://crates.io, to which I get a blank page because of this error.

**Comment by a8nJ** [comment]
Looks like the issue is here:

https://github.com/rust-lang/crates.io/blob/f0794b2b/config/targets.js

where my browser (Waterfox 2020.10) is not listed.

**Comment by Turbo87** [comment]
btw it looks like Waterfox is not yet supported by https://github.com/browserslist/browserslist, which will make this quite hard to solve on our side.

**Comment by a8nJ** [comment]
I think its pretty easy:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator#Browser_compatibility

just make sure Firefox 71 is supported.

**Comment by mansona** [comment]
@a8nJ yes I agree 😂  and to make Firefox 71 supported you need to make sure that Firefox 71 is in your targets file 👍 

For more information, you can see: https://babeljs.io/docs/en/babel-preset-env#targets and I think you would need to make sure that something like this is in your targets file: 

```js
'use strict';

const browsers = [
  'last 1 Chrome versions',
  'last 1 Safari versions'
];

const isCI = Boolean(process.env.CI);
const isProduction = process.env.EMBER_ENV === 'production';

if (isCI || isProduction) {
  browsers.push('ie 11');
}

module.exports = {
  browsers,
  firefox: 71
};
```

Note: this is a slight alteration to the default targets file in an ember app (taken from https://github.com/ember-cli/ember-new-output/blob/master/config/targets.js) and to be honest the firefox specific rule is overkill as by default the production build supports IE 11 (which definitely doesn't natively support nullish coalescing by default)

I'm going to close this for now since a default generated Ember app won't have this problem 👍  let me know if my fix has solved your issue
